### ISSUE TITLE
Subsription is not working offline in android

### ISSUE THREAD

**Issue by Sanghati** [awslabs/aws-mobile-appsync-sdk-android#151]
**Describe the bug**
I subscribe to a mutation in my app , when my app is online the subscription is working fine but in an offline scenario or aeroplane mode when I mutate using console and changing my device mode from offline to online the subscription is not working. My device here is android also I am login using cognito user pool. Kindly help me to find a solution. Below is the error I am facing :
**java.net.UnknownHostException: Unable to resolve host No address associated with hostname**
detailed Message : **failed to execute http call**

**Environment**
 - AppSync SDK Version: 2.7.9

**Comment by palpatim** [comment]
@Sanghati 

There are timing issues to account for when moving from no-network to network scenarios. AppSync implements a lot of handling around these scenarios in its [Delta Sync feature](https://aws-amplify.github.io/docs/android/api#delta-sync). Such timing would make a difference in whether your app successfully receives subscription data when returning to an online state. Can you confirm whether you are using Delta Sync or managing the subscription manually?

Are you canceling and then reconnecting the subscription when you move from no-network to network state? Do you have a small sample app or code snippet that can reproduce the issue to help us narrow down the issue?

**Comment by palpatim** [comment]
@Sanghati Another piece of context: the message you're seeing ("Unable to resolve host No address associated with hostname") means the app is still offline. Please confirm that you have appropriate checks in place to prevent issuing a subscription reconnect until you have reestablished network connectivity.

**Comment by Sanghati** [comment]
> @Sanghati
> 
> There are timing issues to account for when moving from no-network to network scenarios. AppSync implements a lot of handling around these scenarios in its [Delta Sync feature](https://aws-amplify.github.io/docs/android/api#delta-sync). Such timing would make a difference in whether your app successfully receives subscription data when returning to an online state. Can you confirm whether you are using Delta Sync or managing the subscription manually?
> 
> Are you canceling and then reconnecting the subscription when you move from no-network to network state? Do you have a small sample app or code snippet that can reproduce the issue to help us narrow down the issue?

**Comment by Sanghati** [comment]
Kindly let me know what will be the right path to get my offline subscription work.

**Comment by palpatim** [comment]
@Sanghati

To be very explicit: I would never expect a subscription message to be received *while* the device is offline. You would only receive subscriptions when the client is online and able to receive messages from the AppSync backend.

That said, Delta Sync is our recommended solution to let the client manage reconnections. If using the full backend setup, it also reduces overhead by making "catch up" queries upon reconnection rather than a full query.

If you wish to manually manage subscriptions, you'll essentially need to follow DeltaSync's model for handling reconnection behavior. There is no need to create a new client when the network state changes, but you will need to inspect the subscription result handler for disconnection messages and re-register the subscription when the network reconnects. After successful reconnection, you would follow the same logic [Delta Sync](https://aws-amplify.github.io/docs/android/api#delta-sync) uses:

> 1. Subscribe to any queries defined and store results in an incoming queue
> 1. Run the appropriate query (If baseRefreshIntervalInSeconds has elapsed, run the Base Query otherwise only run the Delta Query)
> 1. Update the cache with results from the appropriate query
> 1. Drain the subscription queue and continue processing as normal

Hope this helps.

**Comment by mlykotom** [comment]
I wanted to try the appsync `sync` method, but I was unable due to wrong generic paramaters in the method. I was trying to follow the documentation [here](https://aws-amplify.github.io/docs/android/api), but the real method has signature:
```
public <D extends Query.Data, T, V extends Query.Variables> Cancelable sync(
            @Nonnull Query<D, T, V> baseQuery,
            GraphQLCall.Callback<Query.Data> baseQueryCallback,
            Subscription<D,T,V> subscription,
            AppSyncSubscriptionCall.Callback subscriptionCallback,
            Query<D,T,V> deltaQuery,
            GraphQLCall.Callback<Query.Data> deltaQueryCallback,
            long baseRefreshIntervalInSeconds) {
```

Which means, you have to have `D, T, V` generics the same for base query, subscriptions and delta query. But this is not possible, because you will have different graphql generated classes...

Also another issue is, that the callbacks expect `GraphQLCall.Callback<Query.Data>` which means, you cannot have callback with your data, but must have the base one (and then retyping it to your classes?)
