### ISSUE TITLE
Investigate plugin compatibility with Gradle v6

### ISSUE THREAD

**Issue by desokroshan** [awslabs/aws-mobile-appsync-sdk-android#210]
**Describe the bug**
Android Studio 3.4(Gradle v5) shows deprecation warnings. These deprecations will be removed in v6. This issue is to track investigation and migration of appsync plugin to be compatible with gradle v6

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment(please complete the following information):**
 - AppSync SDK Version: [e.g. 2.6.25]

**Device Information (please complete the following information):**
 - Device: [e.g. Pixel XL, Simulator]
 - Android Version: [e.g. Nougat 7.1.2]
 - Specific to simulators:

**Additional context**

**Comment by vlazdra** [comment]
Hi, I'm unable to use the latest Canary builds of Android studio since they use the newest Gradle version 6 which has a breaking change with AWS App Sync. Specifically the file in question is: https://github.com/awslabs/aws-mobile-appsync-sdk-android/blob/master/aws-android-sdk-appsync-gradle-plugin/src/main/groovy/com/apollographql/apollo/gradle/ApolloPlugin.groovy#L176

Any info on this ?

**Comment by Townk** [comment]
Gradle is already on version 6.2.2 and my team can't migrate to it due to AppSync lack of support. Any plans to fix this? If not, can we use the Apollo plugin for Android to connect to AppSync?

**Comment by polson** [comment]
Also seeing this issue on Android Studio Beta 4

**Comment by hidrodixtion** [comment]
Now that stable Android Studio 4 is released, I believe this should get fixed ASAP. Any tutorial/getting started in using AppSync will be obsoleted as developers can't even add it to their project.

**Comment by jamesonwilliams** [comment]
We have two of these issues floating around. I'm closing this current #210 in favor of #270. Let's track that one.
