### ISSUE TITLE
Mutation are not executed in order

### ISSUE THREAD

**Issue by gitnarqt** [awslabs/aws-mobile-appsync-sdk-android#217]
**State your question**
We've been using AppSync for a while now. Yesterday a client used the app offline for hours and closed the app. As soon as he opened the app and connected to the internet, about 379 mutations were executed. I checked CloudWatch and noticed some mutations were executed more than once at a random moment and I'm confident it has been called only once from the client-side!

The client has very slow internet if this info helps

Are mutations executed one after the other in an order? In what case does a mutation execute twice?

**Environment(please complete the following information):**
 - AppSync SDK Version: 2.7.6

**Comment by palpatim** [comment]
@gitnarqt 

This may not be unexpected behavior. Both the AppSync client and service implement an "at least once" delivery strategy. That is, the sender will attempt a message delivery and expect some confirmation of delivery. If the delivery is not confirmed (e.g., the message sent, but then the network dropped before the recipient responded; or the message was not able to be processed), the message will be re-attempted. In the case of outgoing mutations, that means if there was a problem that prevented the client from detecting a delivery response from the service, the client would attempt to re-send. It would be up to the service and client to handle conflict resolution in cases where the mutation was double-submitted, for example by inspecting a `_version` field.

Since this issue was originally filed, we released [new versions of AppSync](https://github.com/awslabs/aws-mobile-appsync-sdk-android/releases/tag/release_v3.0.1) that uses pure websockets (rather than MQTT over WebSocket) for its client communication. That should be more reliable in some scenarios and might help to resolve some of the duplicate message delivery you're seeing.

If you're still concerned, please feel free to re-open this issue with more details and repro steps if available.
