### ISSUE TITLE
Cognito Token error

### ISSUE THREAD

**Issue by Lishenga** [awslabs/aws-mobile-appsync-sdk-android#319]
Am getting this error when Cognito Pools as an Authentication method "Failed to retrieve Cognito User Pools token."

What could be the issue?

**Comment by richardmcclellan** [comment]
Hi @Lishenga, that error is thrown [here](https://github.com/awslabs/aws-mobile-appsync-sdk-android/blob/198913897c36b6e26e3662bb7301e1a8024f424c/aws-android-sdk-appsync/src/main/java/com/amazonaws/mobileconnectors/appsync/sigv4/AppSyncSigV4SignerInterceptor.java#L148) and typically means you are trying to make a request that requires a Cognito User Pools token, but you don't have one, likely because you are not signed in yet.
