### ISSUE TITLE
Execution failed for task ':app:nodeSetup'.

### ISSUE THREAD

**Issue by kushitani** [awslabs/aws-mobile-appsync-sdk-android#377]
I'm having trouble with a build error.
It occurred when an Android project created on Windows was launched on a mac released this year.

```
Execution failed for task ':app:nodeSetup'.
> Could not resolve all files for configuration ':app:detachedConfiguration3'.
   > Could not find org.nodejs:node:6.7.0.
     Searched in the following locations:
       - https://plugins.gradle.org/m2/org/nodejs/node/6.7.0/node-6.7.0.pom
       - https://dl.google.com/dl/android/maven2/org/nodejs/node/6.7.0/node-6.7.0.pom
       - https://repo.maven.apache.org/maven2/org/nodejs/node/6.7.0/node-6.7.0.pom
       - https://nodejs.org/dist/v6.7.0/node-v6.7.0-darwin-arm64.tar.gz
     Required by:
         project :app

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

The development environment that is occurring.
PC: macOS Monterey
Version: 12.0.1
Chip: m1 pro
AndroidStudio: Android Studio Arctic Fox | 2020.3.1 Patch 3
Gradle Version: 6.7.1
com.amazonaws: aws-android-sdk-appsync-gradle-plugin: 3.2.1

This seems to involve the AppSync library.
Does anyone know the solution?

**Comment by cmunaro** [comment]
I patch that adding
```
android {
    ...
    node { // Undocumented magic that make everything work
        version = "16.14.2"
    }
}
```
I found that solution on stackoverflow but I lost the source :/
I don't know which is the cause

**Comment by shubhams1612** [comment]
Hey could you resolve this issue?? having the same problem. Is it because of the M1 chip??

**Comment by sudhansusekhat** [comment]
@gpanshu I have tried the solution provided by @cmunaro is not working. Tried the same but getting error with the version we used instead of 6.7.0, lets say the solution says need to put this below code on android block in app build.gradle
`node { // Undocumented magic that make everything work
        version = "16.14.2"
    }`
Did this but got error like Could not resolve org.nodejs:node:16.14.2 , same error with 16.14.2 (before 6.7.0)
Please help to get the solution, I have already posted the question on [stackoverflow ](https://stackoverflow.com/questions/75671037/execution-failed-for-task-appnodesetup-could-not-resolve-org-nodejsnode6), please have a look at the question

**Comment by gpanshu** [comment]
Hi @shubhams1612 can you advise what you are using this library for? And please paste in your dependencies for Amplify and AWS so that I can understand where the issue might be.

**Comment by AhmedAshour** [comment]
I have found a solution to this that worked for me:
```
android {
    node {
        distBaseUrl = 'https://direct.nodejs.org/dist/'
    }
}
```
Hope it helps anyone reading this 🙏🏻
