### ISSUE TITLE
When a conflict occurs and ConflictResolver is invoked, GraphQL.Callback is not called back

### ISSUE THREAD

**Issue by mmarceau** [awslabs/aws-mobile-appsync-sdk-android#50]
**Describe the bug**
As a dev, I should be able to fail in a conflict resolver and have that failure come back as an onFailure callback in GraphQL.Callback with a special code telling me the failure was do to a conflict.

**To Reproduce**
1. Create a mutation in AppSync that will conditionally update based on expectedVersion. (i.e. there is a template for this)
2. Execute the mutation on Android client using enqueue with GraphQL.Callback using an object in with an older version number.
3. A conflict occurs on the AppSync backend as expected and and my custom ConflictResolver is invoked on the client.
4. I fail the conflict.
5. GraphQL.Callback is never called back. I have no way of telling my UI to stop waiting.

**Expected behavior**
GraphQL.Callback should be called back in a ConflictResolver failure scenario.

**Environment(please complete the following information):**
 - AppSync SDK Version: 2.6.26

**Device Information (please complete the following information):**
 - Device: Pixel XL API 28 Simulator

**Comment by cbommas** [comment]
@mmarceau 
Just wanted to let you know that I am looking at this issue and will post an update here once I have more information.

**Comment by cbommas** [comment]
@mmarceau 
Version 2.7.5 of the SDK contains changes to address this issue. The callback will be called if you fail a mutation in the conflict resolver code. 

In the onFailure, you can check if the exception is an instance of `ConflictResolutionFailedException` to know that the failure was due to a conflict.  See the following test for an example
https://github.com/awslabs/aws-mobile-appsync-sdk-android/blob/757d8e08ed3576d296e1a6eec972a94b013751b5/aws-android-sdk-appsync-tests/src/androidTest/java/com/amazonaws/mobileconnectors/appsync/AWSAppSyncConflictManagementInstrumentationTest.java#L216

Please give this a try and let us know how it goes.

**Comment by mmarceau** [comment]
Thank you @cbommas - This is now working 👍

**Comment by cbommas** [comment]
@mmarceau 
Good to hear. I will go ahead and close out this issue. Please feel free to post back here ( or create a new issue) if you run into problems.
